form_fileds_mapper = {
  "fill_1[0]": "sp_branch",
  "fill_2[0]": "id_ziadosti",
  "Text1[0]": "nazov_firmy",
  "Text2[0]": "ico_firmy",
  "Text3[0]": "sidlo_firmy_ulica",
  "Text4[0]": "sidlo_firmy_mesto",
  "Text5[0]": "sidlo_firmy_psc",
  "Text6[0]": "sidlo_firmy_stat",
  "Text7[0]": "kontaktna_osoba_firmy",
  "Group1[0].#field[0]": "zamestnanec_pohlavie_muz",
  "Group1[0].#field[1]": "zamestnanec_pohlavie_zena",
  "Text8[0]": "zamestnanec_titul_pred_menom",
  "Text9[0]": "zamestnanec_meno",
  "Text10[0]": "zamestnanec_priezvisko",
  "Text11[0]": "zamestnanec_titul_za_menom",
  "Text12[0]": "zamestnanec_datum_narodenia",
  "Text13[0]": "zamestnanec_miesto_narodenia",
  "Text14[0]": "zamestnanec_statna_prislusnost",
  "Text15[0]": "zamestnanec_rodne_priezvisko",
  "Text16[0]": "zamestnanec_rodne_cislo",
  "Text17[0]": "zamestnanec_adresa_ulica",
  "Text18[0]": "zamestnanec_adresa_mesto",
  "Text19[0]": "zamestnanec_adresa_psc",
  "Text20[0]": "zamestnanec_adresa_stat",
  "Text21[0]": "zamestnanec_tel_cislo",
  "Text22[0]": "zamestnanec_email",
  "Text23[0]": "zamestnanec_cudzinec_doklad_pobyt",
  "Text24[0]": "zamestnanec_cudzinec_pracovne_povolenie",
  "Text25[0]": "zamestnanec_korespondencna_adresa",
  "Text26[0]": "andresa_na_dorucenie_pda1",
  "Group2[0].#field[0]": "uvazok_pracovna_zmluva",
  "Group2[0].#field[1]": "uvazok_dohoda",
  "od": "pracovny_vztah_od",
  "do": "pracovny_vztah_do",
  "Group3[0].#field[0]": "zamestnanec_poisteny_mesiac_spat_ano",
  "Group3[0].#field[1]": "zamestnanec_poisteny_mesiac_spat_nie",
  "Text27[0]": "zamestnanec_pracovna_napln_pred_vyslanim",
  "Group4[0].#field[0]": "zamestnanec_vyslany_jak_kmenovi_ano",
  "Group4[0].#field[1]": "zamestnanec_vyslany_jak_kmenovi_nie",
  "Group5[0].#field[0]": "zamestnanec_vyslany_prideleny_inej_firme_ano",
  "Group5[0].#field[1]": "zamestnanec_vyslany_prideleny_inej_firme_nie",


}
