# Generated by Django 5.2a1 on 2025-02-03 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=150, unique=True)),
                ('head_of_department', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id_employee', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.IntegerField(blank=True, null=True)),
                ('zamestnanec_titul_pred_menom', models.CharField(blank=True, max_length=100, null=True)),
                ('zamestnanec_meno', models.CharField(blank=True, max_length=100, null=True)),
                ('zamestnanec_priezvisko', models.CharField(blank=True, max_length=100, null=True)),
                ('zamestnanec_titul_za_menom', models.CharField(blank=True, max_length=100, null=True)),
                ('zamestnanec_datum_narodenia', models.DateField(blank=True, null=True)),
                ('zamestnanec_miesto_narodenia', models.CharField(blank=True, max_length=100, null=True)),
                ('zamestnanec_statna_prislusnost', models.CharField(blank=True, max_length=100, null=True)),
                ('zamestnanec_rodne_priezvisko', models.CharField(blank=True, max_length=100, null=True)),
                ('zamestnanec_rodne_cislo', models.CharField(blank=True, max_length=20, null=True)),
                ('zamestnanec_adresa_ulica', models.CharField(blank=True, max_length=200, null=True)),
                ('zamestnanec_adresa_mesto', models.CharField(blank=True, max_length=100, null=True)),
                ('zamestnanec_adresa_psc', models.CharField(blank=True, max_length=10, null=True)),
                ('zamestnanec_adresa_stat', models.CharField(blank=True, max_length=100, null=True)),
                ('zamestnanec_tel_cislo', models.CharField(blank=True, max_length=20, null=True)),
                ('zamestnanec_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('zamestnanec_cudzinec_doklad_pobyt', models.CharField(blank=True, max_length=100, null=True)),
                ('zamestnanec_cudzinec_pracovne_povolenie', models.CharField(blank=True, max_length=100, null=True)),
                ('zamestnanec_korespondencna_adresa', models.CharField(blank=True, max_length=200, null=True)),
                ('podpis_zamestnanec_miesto', models.CharField(blank=True, max_length=100, null=True)),
                ('podpis_zamestnanec_datum', models.DateField(blank=True, null=True)),
                ('zamestnanec_pohlavie_muz', models.BooleanField(default=False)),
                ('zamestnanec_pohlavie_zena', models.BooleanField(default=False)),
                ('uvazok_pracovna_zmluva', models.BooleanField(default=False)),
                ('uvazok_dohoda', models.BooleanField(default=False)),
                ('pracovnopravny_vztah_od', models.DateField(blank=True, null=True)),
                ('pracovnopravny_vztah_do', models.CharField(blank=True, max_length=100, null=True)),
                ('zamestnanec_poisteny_mesiac_spat_ano', models.BooleanField(default=False)),
                ('zamestnanec_poisteny_mesiac_spat_nie', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('partner', 'Partner'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pda1',
            fields=[
                ('id_employee_agreement', models.AutoField(primary_key=True, serialize=False)),
                ('zamestnanec_pracovna_napln_pred_vyslanim', models.TextField(blank=True, null=True)),
                ('zamestnanec_vyslany_jak_kmenovi_ano', models.BooleanField(default=False)),
                ('zamestnanec_vyslany_jak_kmenovi_nie', models.BooleanField(default=False)),
                ('zamestnanec_vyslany_od', models.DateField(blank=True, null=True)),
                ('zamestnanec_vyslany_do', models.DateField(blank=True, null=True)),
                ('zamestnanec_druh_cinnosti_pri_vyslani', models.CharField(blank=True, max_length=100, null=True)),
                ('druh_cinnosti_kod_nace', models.CharField(blank=True, max_length=10, null=True)),
                ('andresa_na_dorucenie_pda1', models.CharField(blank=True, max_length=200, null=True)),
                ('zamestnanec_vyslany_prideleny_inej_firme_ano', models.BooleanField(default=False)),
                ('zamestnanec_vyslany_prideleny_inej_firme_nie', models.BooleanField(default=False)),
                ('zamestnanec_subezny_uvazok_inej_firme_ano', models.BooleanField(default=False)),
                ('zamestnanec_subezny_uvazok_inej_firme_nie', models.BooleanField(default=False)),
                ('zamestnanec_odmena_od_kmenovej_firmy_ano', models.BooleanField(default=False)),
                ('zamestnanec_odmena_od_kmenovej_firmy_nie', models.BooleanField(default=False)),
                ('zamestnanec_zadanie_prace_kmenovou_firmou_ano', models.BooleanField(default=False)),
                ('zamestnanec_zadanie_prace_kmenovou_firmou_nie', models.BooleanField(default=False)),
                ('zamestnanec_nahradza_zamestnanca_ano', models.BooleanField(default=False)),
                ('zamestnanec_nahradza_zamestnanca_nie', models.BooleanField(default=False)),
                ('zamestnanec_vystaveny_E101_PDA1_v_inej_krajine_ano', models.BooleanField(default=False)),
                ('zamestnanec_vystaveny_E101_PDA1_v_inej_krajine_nie', models.BooleanField(default=False)),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zentak_legal_automator.employee')),
            ],
            options={
                'db_table': 'employees_agreements',
            },
        ),
        migrations.CreateModel(
            name='Pda1Doc',
            fields=[
                ('pda1_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.FilePathField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zentak_legal_automator.employee')),
            ],
        ),
    ]
