# Generated by Django 5.1.4 on 2025-01-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zentak_legal_automator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("employee", "Employee"),
                            ("partner", "Partner"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
