# Generated by Django 5.1.4 on 2025-01-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zentak_legal_automator", "0002_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="zamestnanec_pracovna_napln_pred_vyslanim",
        ),
        migrations.AddField(
            model_name="employeeagreement",
            name="zamestnanec_pracovna_napln_pred_vyslanim",
            field=models.TextField(blank=True, null=True),
        ),
    ]
