# Generated by Django 5.2a1 on 2025-02-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                ("amount", models.FloatField()),
                ("currency", models.CharField(max_length=10)),
                ("transaction_type", models.CharField(max_length=50)),
                ("counterparty_bank_account", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("category_1", models.CharField(max_length=50)),
                ("category_2", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "transactions",
            },
        ),
    ]
